baseURL: http://example.org/
languageCode: en-us
title: APD
theme: apd

params:
  hero:
    tagline: APD
    subTagline: Vem conhecer o nosso novo website.
    buttonText: Mais info
    image: illustrations/worker.svg
    bottomIcons:
    - logos/clients/systek.svg
    - logos/clients/tribe.svg
    - logos/clients/kromo.svg
    - logos/clients/infinite.svg
    - logos/clients/gutwork.svg
  navbar:
    buttonText: FATT 2019
    logo:
      src: logos/fresh.svg
      alt: Main navbar logo
    links:
    - text: Eventos
      url: /
    - text: Sobre Nós
      url: /
    - text: Sobre Didgeridoo
      dropdown: true
      links:
      - A sua origem ?
      - Como tocar ?
      - Como é construido ?
  features:
    tagline: Vêm conhecer o Festival Didgeridoo - FATT
    subTagline: Mais que um festival... uma filosofia de vida!
    panels:
    - title: Online App builder
      image: illustrations/icons/mouse-globe.svg
      text: This is some explanatory text that is on two rows
      button:
        text: Free Trial
        url: /
      delay: 1
    - title: Cloud deployment
      image: illustrations/icons/laptop-cloud.svg
      text: This is some explanatory text that is on two rows
      button:
        text: Free Trial
        url: /
      delay: 2
    - title: Pluggable tools
      image: illustrations/icons/plug-cloud.svg
      text: This is some explanatory text that is on two rows
      button:
        text: Free Trial
        url: /
      delay: 3
  sellingPoints:
    tagline: Alguns eventos relacionados com o Didgeridoo
    points:
    - title: Evento 1
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: laptop-globe
    - title: Evento 2
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Evento 3
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  platform:
    image: illustrations/mockups/app-mockup.png
    tagline: One Platform to rule them All
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    buttonText: Get Started
  clients:
    tagline: Some feedback from our visitors
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clientExamples:
    - name: Irma Walters
      position: Accountant
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 1.png
    - name: John Bradley
      position: Financial Analyst
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 2.png
    - name: Gary Blackman
      position: HR Manager
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 3.png
  contact:
    tagline: Drop us a line or two!
  footer:
    image: fresh-white.svg
    columns:
    - title: Product
      links:
      - name: Discover features
        url: "#"
      - name: Why choose our Product?
        url: "#"
      - name: Compare features
        url: "#"
      - name: Our Roadmap
        url: "#"
      - name: Request features
        url: "#"
    - title: Docs
      links:
      - name: Get Started
        url: "#"
      - name: User guides
        url: "#"
      - name: Admin guide
        url: "#"
      - name: Developers
        url: "#"
    - title: Blogroll
      links:
      - name: Latest News
        url: "#"
      - name: Tech articles
        url: "#"
      - name: Video Blog
        url: "#"
    followUs:
    - icon: github
      url: "https://github.com/lucperkins"
    - icon: dribbble
      url: "#"
    - icon: facebook
      url: "#"
    - icon: twitter
      url: "https://twitter.com/lucperkins"
    - icon: bitbucket
      url: "#"
