name = "APD"
license = "MIT"
licenselink = "https://github.com/exodon/APD-website"
description = ""
homepage = "https://github.com/exodon/APD-website"
tags = ["responsive", "one page", "light", "onepage", "company", "clean", "landing page"]
features = []
min_version = "0.1"

[author]
  name = "Ricardo Branco"
  homepage = "https://github.com/exodon"
